name: Users API

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  prebuild:
    name: Build app distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: NPM cmds
        run: |
          npm install
          npm run build ./udagram-frontend/package.json
        working-directory: ./api/users-service

  build:
    name: Build pro app
    runs-on: ubuntu-latest
    needs: [prebuild]
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the Docker image
        run: docker build --rm -f "./api/users-service/Dockerfile" -t byblix/project3_users-api:latest .

      - name: Push the Docker image to the registry
        run: docker push byblix/project3_users-api:latest
